### ISSUE TITLE
Map crahsing: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [kubernetes-sigs/headlamp#2534]
## Describe the bug
Map is not working

## To Reproduce
Steps to reproduce the bug:
Go to map

## Environment (please provide info about your environment):
 - Installation type: Downloaded OSX ARM binary
 - Headlamp Version: 0.26.0

## Are you able to fix this issue?
No

## Additional Context

We have a big cluster, around 500 namespaces and 1200 pods / 500 deployments

```error
RangeError: Maximum call stack size exceeded
    at file:///Applications/Headlamp.app/Contents/Resources/frontend/assets/GraphView-C5xOIooh.js:43:226311
    at Set.forEach (<anonymous>)
    at file:///Applications/Headlamp.app/Contents/Resources/frontend/assets/GraphView-C5xOIooh.js:43:226235
    at UJn (file:///Applications/Headlamp.app/Contents/Resources/frontend/assets/GraphView-C5xOIooh.js:43:225328)
    at VJn (file:///Applications/Headlamp.app/Contents/Resources/frontend/assets/GraphView-C5xOIooh.js:43:226199)
    at pm (file:///Applications/Headlamp.app/Contents/Resources/frontend/assets/vendor-mui-DuPX71-Q.js:38:17018)
    at Vp (file:///Applications/Headlamp.app/Contents/Resources/frontend/assets/vendor-mui-DuPX71-Q.js:40:3139)
    at rx (file:///Applications/Headlamp.app/Contents/Resources/frontend/assets/vendor-mui-DuPX71-Q.js:40:44833)
    at tx (file:///Applications/Headlamp.app/Contents/Resources/frontend/assets/vendor-mui-DuPX71-Q.js:40:39790)
    at WR (file:///Applications/Headlamp.app/Contents/Resources/frontend/assets/vendor-mui-DuPX71-Q.js:40:39718)
    at Kc (file:///Applications/Headlamp.app/Contents/Resources/frontend/assets/vendor-mui-DuPX71-Q.js:40:39570)
    at tf (file:///Applications/Headlamp.app/Contents/Resources/frontend/assets/vendor-mui-DuPX71-Q.js:40:35934)
    at Zb (file:///Applications/Headlamp.app/Contents/Resources/frontend/assets/vendor-mui-DuPX71-Q.js:40:34883)
    at R (file:///Applications/Headlamp.app/Contents/Resources/frontend/assets/vendor-mui-DuPX71-Q.js:25:1574)
    at MessagePort.B (file:///Applications/Headlamp.app/Contents/Resources/frontend/assets/vendor-mui-DuPX71-Q.js:25:1942)
```

**Comment by sniok** [comment]
Thanks for filing an issue! I'll look into this

**Comment by sniok** [comment]
Fixed in https://github.com/kubernetes-sigs/headlamp/pull/2538
